name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc

    - name: Make bundled qbe executable
      run: |
        chmod +x ci-bin/qbe
        echo "${{ github.workspace }}/ci-bin" >> $GITHUB_PATH

    - name: Check qbe workability
      run: qbe -h


    - name: Install LLVM 21
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
        sudo apt install -y llvm-21-dev libclang-21-dev

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-registry-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-${{ runner.os }}-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-build-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-build-${{ runner.os }}-

    - name: Build
      run: cargo build --verbose

    - name: Run Tests (QBE Backend)
      run: FCY_BACKEND=qbe cargo test --verbose
    
    - name: Run Tests (LLVM Backend)
      run: FCY_BACKEND=llvm cargo test --verbose




